#!/usr/bin/env python3
# Regenerates the Machinedrum Editor skin's markup and stylesheet
# (source/elektron/md/mdJucePlugin/skins/mdStudio/mdStudio.html, mdDesk.css)
# from the approved mockup, doc/modern-ux/mockup/index.html, so a design round
# needs this script plus the behaviour the round changed in mdDeskApp.js.
#   python3 doc/modern-ux/sync-mdstudio-skin.py          write the skin
#   python3 doc/modern-ux/sync-mdstudio-skin.py --check  only report drift
#
# What it does, in order:
#  1. Markup: the mockup's <div class="app"> as is, plus the real machine's
#     status and error lines. Mockup-only elements (the first-run preview link,
#     the rules footer) are dropped if a round brings them back. Controls the
#     real machine cannot do yet are marked disabled here (HONEST below), so
#     the page never offers them.
#  2. Stylesheet: the mockup's, with local fonts instead of Google Fonts, then
#     the P2/P3 states at the end.
#  3. Contract check: every element id the page's scripts look up must exist
#     in the markup or be made by the scripts. A design round that renames or
#     drops one fails here instead of in the plug-in.
# The mockup's script is example state and is never copied.
import os
import re
import sys

R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..') + '/'
SK = R + 'source/elektron/md/mdJucePlugin/skins/mdStudio/'
check_only = '--check' in sys.argv

src = open(R + 'doc/modern-ux/mockup/index.html').read()
css = src[src.index('<style>') + 7:src.index('</style>')]
m = src[src.index('<div class="app">'):src.index('<script>')]

# ---- 1. markup ----
MOCK_ONLY = [r'<p class="firstlink">.*?</p>\s*', r'<details class="rules">.*?</details>\s*']
for pattern in MOCK_ONLY:
    m = re.sub(pattern, '', m, flags=re.S)
BODY = '  <div class="body" id="body">'
assert BODY in m, 'mockup: no #body'
m = m.replace(BODY, '  <p class="statusline" id="status" role="status" hidden></p>\n'
              '  <p class="errline" id="errline" role="alert" hidden></p>\n' + BODY)
# Controls the machine cannot do yet: (mockup text, skin text). Each must match.
HONEST = [
    # P4: HW MIDI is real (the plug-in's MIDI in/out); nothing to disable here now.
]
for a, b in HONEST:
    assert a in m, 'mockup changed: ' + a
    m = m.replace(a, b)
# The page's modules, in load order (a module that does not exist yet is skipped).
# mdDeskSelfTest.js last: the self-tests, in the plug-in only with the diagnostics (an empty script otherwise).
SCRIPTS = ['mdDeskModal.js', 'mdDeskBoot.js', 'mdDeskSyx.js', 'mdDeskBridge.js', 'mdDeskModel.js', 'mdDeskKeys.js', 'mdDeskMod.js', 'mdDeskApp.js', 'mdDeskLive.js', 'mdDeskLibrary.js', 'mdDeskGlobal.js', 'mdDeskAudio.js', 'mdDeskSelfTest.js']
title = re.search(r'<title>(.*?)</title>', src).group(1)
page = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>%s</title>
<!-- The Machinedrum Editor page: the approved mockup
     doc/modern-ux/mockup/index.html on the plug-in's documents. Markup and
     stylesheet are generated by doc/modern-ux/sync-mdstudio-skin.py; do not
     edit them by hand. The editor inlines the stylesheet, scripts and any
     bundled fonts before loading (WKWebView reads only this file). -->
<link rel="stylesheet" href="mdDesk.css">
</head>
<body>
%s
%s
</body>
</html>
''' % (title, m.rstrip(), '\n'.join('<script src="%s"></script>' % f for f in SCRIPTS if os.path.exists(SK + f)))

# ---- 2. stylesheet ----
head = """/* Machinedrum Editor stylesheet: the mockup's (doc/modern-ux/mockup/index.html)
   as is, with bundled fonts instead of Google Fonts and the real machine's
   states at the end. Generated by doc/modern-ux/sync-mdstudio-skin.py. Fonts:
   Barlow Condensed, IBM Plex Mono and Silkscreen, SIL Open Font License 1.1,
   in skins/mdStudio/fonts/ with their OFL-*.txt; the editor inlines them. */
@font-face{font-family:"Barlow Condensed";font-weight:500;src:url("fonts/BarlowCondensed-Medium.ttf") format("truetype")}
@font-face{font-family:"Barlow Condensed";font-weight:600 700;src:url("fonts/BarlowCondensed-SemiBold.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:400;src:url("fonts/IBMPlexMono-Regular.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:500 700;src:url("fonts/IBMPlexMono-Medium.ttf") format("truetype")}
@font-face{font-family:"Silkscreen";font-weight:400 700;src:url("fonts/Silkscreen-Regular.ttf") format("truetype")}
"""
for a, b in [('--sans:"Barlow Condensed","Arial Narrow",system-ui,sans-serif;',
              '--sans:"Barlow Condensed","Avenir Next Condensed","Arial Narrow",system-ui,sans-serif;'),
             ('--mono:"IBM Plex Mono",ui-monospace,Menlo,monospace;', '--mono:"IBM Plex Mono",Menlo,ui-monospace,monospace;'),
             ('--pix:"Silkscreen",ui-monospace,monospace;', '--pix:"Silkscreen",Menlo,ui-monospace,monospace;')]:
    assert a in css, a
    css = css.replace(a, b)
css = re.sub(r'@import url\([^)]*fonts\.googleapis[^)]*\);?\s*', '', css)
tail = '''
/* ===== The real machine's states (not in the mockup) ===== */
.st.past{opacity:.45}
.st.lkpend{outline:2px dashed var(--led);outline-offset:-2px}
.statusline,.errline{margin:6px 0 0;padding:6px 10px;border-radius:3px;font:12px var(--pix);text-transform:uppercase}
.statusline{background:var(--lcd);color:var(--ink)}
.errline{background:var(--rec);color:#fff}
.kopt:disabled,button[data-na]{opacity:.45;cursor:not-allowed}
.lcdeng .led:not(.on){opacity:.35}
body.liverec .st,body.liverec .lb{cursor:cell}
.recbadge{font:10px var(--pix);text-transform:uppercase;color:var(--rec)}
/* Control side panel: the title on one line, the description under it. */
.ctlui .card>header{flex-direction:column!important;align-items:flex-start!important;gap:2px!important}
.ctlui .card>header h3{white-space:nowrap}
/* LCD transport keys: an explicit square tied to the LCD height. The mockup's
   aspect-ratio on a stretched height collapsed to slivers in the plug-in's
   WebKit, so no aspect-ratio and no stretch here. */
.top{--ltk:calc(var(--lcdh) - 28px)}
.lcdpanel .trf{display:flex!important;flex-direction:column!important;justify-content:flex-start!important;align-items:flex-start!important;gap:3px!important}
.lcdt{display:flex!important;flex-direction:row!important;flex-wrap:nowrap!important;align-items:flex-start!important;align-self:flex-start!important;gap:5px!important}
.lcdt .lt{flex:0 0 var(--ltk)!important;width:var(--ltk)!important;height:var(--ltk)!important;min-width:var(--ltk)!important;min-height:var(--ltk)!important;aspect-ratio:auto!important;box-sizing:border-box!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important}
/* P9: a slot's waveform with its audition key (the LCD keys' look) and playhead. The box takes the
   canvas' place, so the Sound screen's stretch rules apply to it. */
.wavebox{position:relative;min-width:0}
.wavebox>canvas.ed{width:100%}
.soundgrid>.card>.wavebox{min-height:150px}
.soundgrid>.card>.wavebox>canvas.ed{height:100%!important;min-height:150px}
.wavebox .aud{all:unset;position:absolute;top:6px;right:6px;cursor:pointer;display:inline-flex;align-items:center;gap:4px;height:18px;padding:0 6px;border-radius:2px;
  font:12px var(--pix);text-transform:uppercase;color:var(--ink);background:var(--lcd);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--ink) 55%,transparent)}
.wavebox .aud svg{width:8px;height:8px;fill:currentColor}
.wavebox .aud:hover{background:color-mix(in srgb,var(--ink) 15%,var(--lcd))}
.wavebox .aud[aria-pressed=true]{background:var(--ink);color:var(--lcd)}
.wavebox .aud:focus-visible{outline:2px solid var(--ink);outline-offset:1px}
.wavebox .aud:disabled{opacity:.45;cursor:not-allowed}
.wavebox .audph{position:absolute;left:0;top:0;bottom:0;width:0;pointer-events:none;border-radius:4px 0 0 4px;
  background:color-mix(in srgb,var(--ink) 12%,transparent);box-shadow:inset -2px 0 0 var(--ink)}
.wavebox .audph[hidden]{display:none}
'''
out_css = head + css.strip('\n') + '\n' + tail

# ---- 3. contract check: ids the scripts look up ----
scripts = ''.join(open(SK + f).read() for f in os.listdir(SK) if f.endswith('.js'))
wanted = (set(re.findall(r'\$\("#([A-Za-z][\w-]*)', scripts)) | set(re.findall(r'getElementById\("([\w-]+)"\)', scripts))
          | set(re.findall(r'closest\("#([A-Za-z][\w-]*)"\)', scripts)))
made = (set(re.findall(r'id="([A-Za-z][\w-]*)"', scripts)) | set(re.findall(r'id=\\"([\w-]+)', scripts))
        | set(re.findall(r'\.id\s*=\s*"([\w-]+)"', scripts)))
present = set(re.findall(r'id="([\w-]+)"', m))
# the MIDI mapping UI (the Control tab, LEARN) is out of the markup until the controller feature (FOUNDATION.md)
optional = {'learnkey'}
missing = sorted(wanted - present - made - optional)
if missing:
    print('contract check: the page looks up ids the mockup markup no longer has:', ', '.join(missing))
    sys.exit(1)

# ---- the shared AUDIO / MIDI panel: one text in every copy ----
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import audio_panel_check
panel = audio_panel_check.check(R)
import modal_check
panel += modal_check.check(R)
if panel:
    print('AUDIO / MIDI panel: ' + '; '.join(panel))
    sys.exit(1)

# ---- the pages against the contract: the ops they send, their arguments, the capabilities ----
import page_contract_check as pc
schema = pc.load(R + 'doc/modern-ux/md-data-contract.schema.json')
table = pc.command_table(schema)
page_js = {f: open(SK + f).read() for f in SCRIPTS if os.path.exists(SK + f)}
problems = []
for f, text in page_js.items():
    sends = []
    for args in pc.calls(text, 'cmd'):
        keys = pc.object_keys(args[1]) if len(args) > 1 and args[1].startswith('{') else (set() if len(args) == 1 else None)
        sends.append((pc.ops_of(args[0]), keys))
    for args in pc.calls(text, 'songCmd'):
        keys = pc.object_keys(args[1]) if len(args) > 1 and args[1].startswith('{') else None
        sends.append((pc.ops_of(args[0]), None if keys is None else keys | {'s'}))
    sends += list(pc.literals_with_op(text))
    problems += pc.check_sends(sends, table, f)
    problems += pc.check_audio(text, table, f)
app = page_js['mdDeskApp.js']
cap_table = re.search(r'const CAP_CONTROLS = \{(.*?)\};', app, re.S)
cap_info = re.search(r'const CAP_INFO = \[(.*?)\];', app, re.S)
if not cap_table or not cap_info:
    problems.append('mdDeskApp.js: no CAP_CONTROLS / CAP_INFO')
else:
    problems += pc.check_caps(re.findall(r'^\s*(\w+):', cap_table.group(1), re.M), re.findall(r'"(\w+)"', cap_info.group(1)), schema, 'mdDeskApp.js')
# LIFE (machine.lifecycle -> the page's words) and the message types onMessage handles, both
# against the contract, both ways (a page can gate on nothing the contract will never send, and
# nothing the contract sends can go unhandled).
life = pc.find_object(app, 'LIFE')
if life is None:
    problems.append('mdDeskApp.js: no LIFE')
else:
    problems += pc.check_lifecycle(pc.object_keys(life) or set(), schema, 'mdDeskApp.js')
problems += pc.check_mapping_gate(app, ['S.mapping = false;', 'applyMapping(m.doc.enabled)', 'when: () => S.mapping && S.ctl.learn',
                                        'mapping: ws === "control", when: ws === "control" ? () => S.mapping : null',
                                        'does: "LEARN: map a value to a controller knob", mapping: true, when: () => S.mapping',
                                        'tb.dataset.ws === "control" && !S.mapping'], 'mdDeskApp.js')
all_js = ''.join(page_js.values())
problems += pc.check_message_types(pc.message_types_handled(all_js), schema, 'mdStudio')
if problems:
    print('contract check: ' + '; '.join(problems))
    sys.exit(1)

if check_only:
    now_html = open(SK + 'mdStudio.html').read()
    now_css = open(SK + 'mdDesk.css').read()
    drift = [n for n, a, b in [('mdStudio.html', now_html, page), ('mdDesk.css', now_css, out_css)] if a != b]
    print('drift: ' + ', '.join(drift) if drift else 'in step with the mockup')
    sys.exit(1 if drift else 0)
open(SK + 'mdStudio.html', 'w').write(page)
open(SK + 'mdDesk.css', 'w').write(out_css)
print('synced: %d bytes markup, %d bytes stylesheet, %d ids checked' % (len(page), len(out_css), len(wanted)))
