#!/usr/bin/env python3
# Regenerates the Monomachine Editor skin (source/elektron/md/mdJucePlugin/skins/mmStudio/:
# mmStudio.html, mmStudio.css, mmMockup.js) from the approved mockup in
# doc/modern-ux/mm-mockup/src/ (copy the design source there first).
#   python3 doc/modern-ux/sync-mmstudio-skin.py          write the skin
#   python3 doc/modern-ux/sync-mmstudio-skin.py --check  only report drift
#
# Unlike the MD skin, the mockup's own script runs in the plug-in: it is the UI, copied as it
# is (P6: no patches). It hands what the machine does to its host (src/55-host.js):
# mmAdapter.js (hand-written, loaded before it) is the plug-in's host and uses the view through
# window.MMView. What the engine cannot do comes from the machine's capabilities at run time.
#  1. Markup: 30-body.html as it is.
#  2. Stylesheet: 10-md-base.css + 20-mm.css, bundled fonts instead of Google
#     Fonts, then the real machine's states.
#  3. Script: 40-data.js .. 130-main.js in build.sh order, as they are.
#  4. Contract check: every MMView member and id mmAdapter.js uses exists, and every host call
#     the adapter implements is one the mockup makes.
import os
import re
import sys

R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..') + '/'
SRC = R + 'doc/modern-ux/mm-mockup/src/'
SK = R + 'source/elektron/md/mdJucePlugin/skins/mmStudio/'
check_only = '--check' in sys.argv

build = open(R + 'doc/modern-ux/mm-mockup/build.sh').read()
css_files = re.findall(r'src/(\d+-[\w-]+\.css)', build)
js_files = re.findall(r'src/(\d+-[\w-]+\.js)', build)
body_file = re.search(r'src/(\d+-body\.html)', build).group(1)
title = re.search(r'<title>(.*?)</title>', build).group(1)

# ---- 1. markup ----
m = open(SRC + body_file).read()
# The host first (it defines window.MMHost, which the mockup reads when it loads), then the UI, then
# the translation (it reads the mockup's tables).
# mmSelfTest.js last: the self-tests, in the plug-in only with the diagnostics (an empty script otherwise).
SCRIPTS = ['mdDeskBridge.js', 'mmAdapter.js', 'mmMockup.js', 'mmConvert.js', 'mmSelfTest.js']
page = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>%s</title>
<!-- The Monomachine Editor page: the approved mockup (doc/modern-ux/mm-mockup)
     played by the plug-in: mmAdapter.js is its host (P6). Markup, stylesheet and
     mmMockup.js are copied by doc/modern-ux/sync-mmstudio-skin.py; do not edit
     them by hand. The editor inlines stylesheet, scripts and fonts. -->
<link rel="stylesheet" href="mmStudio.css">
</head>
<body>
%s
%s
</body>
</html>
''' % (title, m.rstrip(), '\n'.join('<script src="%s"></script>' % f for f in SCRIPTS))

# ---- 2. stylesheet ----
css = ''.join(open(SRC + f).read() for f in css_files)
head = """/* Monomachine Editor stylesheet: the mockup's (doc/modern-ux/mm-mockup) as is,
   with bundled fonts instead of Google Fonts and the real machine's states at
   the end. Generated by doc/modern-ux/sync-mmstudio-skin.py. Fonts: Barlow
   Condensed, IBM Plex Mono and Silkscreen, SIL Open Font License 1.1, shared with
   the Machinedrum Editor (skins/mdStudio/fonts/, with their OFL-*.txt). */
@font-face{font-family:"Barlow Condensed";font-weight:500;src:url("fonts/BarlowCondensed-Medium.ttf") format("truetype")}
@font-face{font-family:"Barlow Condensed";font-weight:600 700;src:url("fonts/BarlowCondensed-SemiBold.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:400;src:url("fonts/IBMPlexMono-Regular.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:500 700;src:url("fonts/IBMPlexMono-Medium.ttf") format("truetype")}
@font-face{font-family:"Silkscreen";font-weight:400 700;src:url("fonts/Silkscreen-Regular.ttf") format("truetype")}
"""
css = re.sub(r'@import url\([^)]*fonts\.googleapis[^)]*\);?\s*', '', css)
tail = '''
/* ===== The real machine's states (not in the mockup) ===== */
/* While the firmware starts, the LCD shows the machine's own screen (mmAdapter.js). */
.bootscr.fw{padding:0;gap:0;place-items:center;align-content:center;transition:opacity .45s ease}
.bootscr.fw>*:not(canvas){display:none}
.bootscr canvas.fwlcd{height:100%;max-width:100%;image-rendering:pixelated;image-rendering:crisp-edges}
.bootscr.fading{opacity:0}
.statusline,.errline{margin:6px 0 0;padding:6px 10px;border-radius:3px;font:12px var(--pix);text-transform:uppercase}
.statusline{background:var(--lcd);color:var(--ink)}
.errline{background:var(--rec,#c43);color:#fff}
/* What the editor cannot do yet (mmAdapter.js marks it, with the reason as the tooltip). */
[data-na]{opacity:.42!important;cursor:not-allowed!important}
[data-na] [data-na]{opacity:1!important}
.lcdeng .led:not(.on){opacity:.35}
/* LCD transport keys (as the MD skin, P3/P5): an explicit square tied to the LCD height. The
   mockup's aspect-ratio on a stretched height collapsed to slivers in the plug-in's WebKit, so no
   aspect-ratio and no stretch here. */
.top{--ltk:calc(var(--lcdh) - 30px)}
.lcdpanel .trf{display:flex!important;flex-direction:column!important;justify-content:flex-start!important;align-items:flex-start!important;gap:3px!important}
.lcdt{display:flex!important;flex-direction:row!important;flex-wrap:nowrap!important;align-items:flex-start!important;align-self:flex-start!important;gap:5px!important}
.lcdt .lt{flex:0 0 var(--ltk)!important;width:var(--ltk)!important;height:var(--ltk)!important;min-width:var(--ltk)!important;min-height:var(--ltk)!important;aspect-ratio:auto!important;box-sizing:border-box!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important}
/* The MKII print sits inside the header, above its bottom rule. */
:root[data-plate="mk2"] .lcdgroup::after{bottom:-7px!important}
'''
out_css = head + css.strip('\n') + '\n' + tail

# ---- 3. script ----
js = ''
for f in js_files:
    js += '/* ---- %s ---- */\n' % f + open(SRC + f).read() + '\n'
out_js = '/* Generated by doc/modern-ux/sync-mmstudio-skin.py from doc/modern-ux/mm-mockup/src. Do not edit. */\n' + js

# ---- 4. contract check ----
adapter = open(SK + 'mmAdapter.js').read()
# the self-tests drive the same view (checked with the adapter; the host block is the adapter's)
uses = adapter + open(SK + 'mmSelfTest.js').read()
view = re.search(r'window\.MMView=\{(.*?)\};\n', js, re.S)
exported = set(re.findall(r'(\w+)(?=[,:}]|$)', view.group(1))) if view else set()
used = set(re.findall(r'V\(\)\.(\w+)', uses)) | set(re.findall(r'(?<![.\w])v\.(\w+)', adapter))
missing = sorted(used - exported)
host_calls = set(re.findall(r'HOST\.(\w+)', js))
host_block = adapter[adapter.index('window.MMHost = {'):]
host_block = host_block[:host_block.index('\n\t};\n')]
host_methods = set(re.findall(r'^\t\t(\w+)(?:\(|:)', host_block, re.M))
unused = sorted(host_methods - host_calls)
wanted = set(re.findall(r'\$\("#([A-Za-z][\w-]*)', uses)) | set(re.findall(r'getElementById\("([\w-]+)"\)', uses))
present = set(re.findall(r'id="([\w-]+)"', m)) | set(re.findall(r'id=\\?"([\w-]+)', js))
missing_ids = sorted(wanted - present)
if missing or missing_ids or unused:
    print('contract check: mmAdapter.js uses MMView.' + ', MMView.'.join(missing) if missing else '', '#' + ' #'.join(missing_ids) if missing_ids else '',
          ('host calls the mockup does not make: ' + ', '.join(unused)) if unused else '')
    sys.exit(1)

outs = [('mmStudio.html', page), ('mmStudio.css', out_css), ('mmMockup.js', out_js)]
if check_only:
    drift = [n for n, text in outs if not os.path.exists(SK + n) or open(SK + n).read() != text]
    print('drift: ' + ', '.join(drift) if drift else 'in step with the mockup')
    sys.exit(1 if drift else 0)
for n, text in outs:
    open(SK + n, 'w').write(text)
print('synced: %d bytes markup, %d bytes stylesheet, %d bytes script; %d view members, %d host calls and %d ids checked'
      % (len(page), len(out_css), len(out_js), len(used), len(host_methods), len(wanted)))
