#!/usr/bin/env python3
# Regenerates the Monomachine Editor skin (source/elektron/md/mdJucePlugin/skins/mmStudio/:
# mmStudio.html, mmStudio.css, mmMockup.js) from the approved mockup in
# doc/modern-ux/mm-mockup/src/ (copy the design source there first).
#   python3 doc/modern-ux/sync-mmstudio-skin.py          write the skin
#   python3 doc/modern-ux/sync-mmstudio-skin.py --check  only report drift
#
# Unlike the MD skin, the mockup's own script runs in the plug-in: it is the UI, copied as it
# is (P6: no patches). It hands what the machine does to its host (src/55-host.js):
# mmAdapter.js (hand-written, loaded before it) is the plug-in's host and uses the view through
# window.MMView. What the engine cannot do comes from the machine's capabilities at run time.
#  1. Markup: 30-body.html as it is.
#  2. Stylesheet: 10-md-base.css + 20-mm.css, bundled fonts instead of Google
#     Fonts, then the real machine's states.
#  3. Script: 40-data.js .. 130-main.js in build.sh order, as they are.
#  4. Contract check: every MMView member and id mmAdapter.js uses exists (the self-tests,
#     mmSelfTest.js, are checked on their own), the adapter never touches the view's state
#     (S(), MMView.S, LIB, ENG, H, the panel's globals) nor its markup ($(, $$(, document.),
#     the view exports no state or test (S, audioSelfTest: a diagnostics build's MMDiagnostics
#     only), and the host calls match both ways: the mockup makes no HOST.* call the adapter
#     lacks, and the adapter has no host call the mockup never makes.
#  5. The pages against the contract (page_contract_check.py): every op the adapter sends is in
#     $defs/command with only its declared arguments, the panel's audioSet arguments too, and the
#     mockup's NA_SEL plus NA_INFO name exactly the contract's capabilities.
import os
import re
import sys

R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..') + '/'
SRC = R + 'doc/modern-ux/mm-mockup/src/'
SK = R + 'source/elektron/md/mdJucePlugin/skins/mmStudio/'
check_only = '--check' in sys.argv
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import modal_check
_modal = modal_check.check(R)
if _modal:
    print('modal layer: ' + '; '.join(_modal))
    sys.exit(1)

build = open(R + 'doc/modern-ux/mm-mockup/build.sh').read()
css_files = re.findall(r'src/(\d+-[\w-]+\.css)', build)
js_files = re.findall(r'src/(\d+-[\w-]+\.js)', build)
body_file = re.search(r'src/(\d+-body\.html)', build).group(1)
title = re.search(r'<title>(.*?)</title>', build).group(1)

# ---- 1. markup ----
m = open(SRC + body_file).read()
# The host first (it defines window.MMHost, which the mockup reads when it loads), then the UI, then
# the translation (it reads the mockup's tables).
# mmSelfTest.js before the mockup: the self-tests, in the plug-in only with the diagnostics (an empty
# script otherwise); it sets window.MMDiagnostics, where the mockup puts what only tests may touch.
SCRIPTS = ['mdDeskBridge.js', 'mmAdapter.js', 'mmSelfTest.js', 'mmMockup.js', 'mmConvert.js']
page = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>%s</title>
<!-- The Monomachine Editor page: the approved mockup (doc/modern-ux/mm-mockup)
     played by the plug-in: mmAdapter.js is its host (P6). Markup, stylesheet and
     mmMockup.js are copied by doc/modern-ux/sync-mmstudio-skin.py; do not edit
     them by hand. The editor inlines stylesheet, scripts and fonts. -->
<link rel="stylesheet" href="mmStudio.css">
</head>
<body>
%s
%s
</body>
</html>
''' % (title, m.rstrip(), '\n'.join('<script src="%s"></script>' % f for f in SCRIPTS))

# ---- 2. stylesheet ----
css = ''.join(open(SRC + f).read() for f in css_files)
head = """/* Monomachine Editor stylesheet: the mockup's (doc/modern-ux/mm-mockup) as is,
   with bundled fonts instead of Google Fonts and the real machine's states at
   the end. Generated by doc/modern-ux/sync-mmstudio-skin.py. Fonts: Barlow
   Condensed, IBM Plex Mono and Silkscreen, SIL Open Font License 1.1, shared with
   the Machinedrum Editor (skins/mdStudio/fonts/, with their OFL-*.txt). */
@font-face{font-family:"Barlow Condensed";font-weight:500;src:url("fonts/BarlowCondensed-Medium.ttf") format("truetype")}
@font-face{font-family:"Barlow Condensed";font-weight:600 700;src:url("fonts/BarlowCondensed-SemiBold.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:400;src:url("fonts/IBMPlexMono-Regular.ttf") format("truetype")}
@font-face{font-family:"IBM Plex Mono";font-weight:500 700;src:url("fonts/IBMPlexMono-Medium.ttf") format("truetype")}
@font-face{font-family:"Silkscreen";font-weight:400 700;src:url("fonts/Silkscreen-Regular.ttf") format("truetype")}
"""
css = re.sub(r'@import url\([^)]*fonts\.googleapis[^)]*\);?\s*', '', css)
tail = '''
/* ===== The real machine's states (not in the mockup) ===== */
.statusline,.errline{margin:6px 0 0;padding:6px 10px;border-radius:3px;font:12px var(--pix);text-transform:uppercase}
.statusline{background:var(--lcd);color:var(--ink)}
.errline{background:var(--rec,#c43);color:#fff}
/* What the editor cannot do yet (mmAdapter.js marks it, with the reason as the tooltip). */
[data-na]{opacity:.42!important;cursor:not-allowed!important}
[data-na] [data-na]{opacity:1!important}
.lcdeng .led:not(.on){opacity:.35}
/* LCD transport keys (as the MD skin, P3/P5): an explicit square tied to the LCD height. The
   mockup's aspect-ratio on a stretched height collapsed to slivers in the plug-in's WebKit, so no
   aspect-ratio and no stretch here. */
.top{--ltk:calc(var(--lcdh) - 30px)}
.lcdpanel .trf{display:flex!important;flex-direction:column!important;justify-content:flex-start!important;align-items:flex-start!important;gap:3px!important}
.lcdt{display:flex!important;flex-direction:row!important;flex-wrap:nowrap!important;align-items:flex-start!important;align-self:flex-start!important;gap:5px!important}
.lcdt .lt{flex:0 0 var(--ltk)!important;width:var(--ltk)!important;height:var(--ltk)!important;min-width:var(--ltk)!important;min-height:var(--ltk)!important;aspect-ratio:auto!important;box-sizing:border-box!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important}
'''
out_css = head + css.strip('\n') + '\n' + tail

# ---- 3. script ----
js = ''
for f in js_files:
    js += '/* ---- %s ---- */\n' % f + open(SRC + f).read() + '\n'
out_js = '/* Generated by doc/modern-ux/sync-mmstudio-skin.py from doc/modern-ux/mm-mockup/src. Do not edit. */\n' + js

# ---- 4. contract check ----
# The product seam is checked from mmAdapter.js alone (a release page has no self-tests); the
# self-tests (mmSelfTest.js, diagnostics builds) are checked on their own against the same view.
adapter = open(SK + 'mmAdapter.js').read()
selftest = open(SK + 'mmSelfTest.js').read()
view = re.search(r'window\.MMView=\{(.*?)\};\n', js, re.S)
exported = set(re.findall(r'(\w+)(?=[,:}]|$)', re.sub(r'/\*.*?\*/', '', view.group(1), flags=re.S))) if view else set()
present = set(re.findall(r'id="([\w-]+)"', m)) | set(re.findall(r'id=\\?"([\w-]+)', js)) | set(re.findall(r'\.id = "([\w-]+)"', js))


def seam(text, name):
    """what one script uses of the view and the markup that the mockup does not have"""
    used = set(re.findall(r'V\(\)\.(\w+)', text)) | set(re.findall(r'(?<![.\w])v\.(\w+)', text))
    wanted = set(re.findall(r'\$\("#([A-Za-z][\w-]*)', text)) | set(re.findall(r'getElementById\("([\w-]+)"\)', text))
    out = ['%s uses MMView.%s' % (name, x) for x in sorted(used - exported)]
    out += ['%s uses #%s' % (name, x) for x in sorted(wanted - present)]
    return out, used, wanted


problems, used, wanted = seam(adapter, 'mmAdapter.js')
test_problems, test_used, test_wanted = seam(selftest, 'mmSelfTest.js')
problems += test_problems
# the adapter reads the view through values and setters, never its state
if re.search(r'\bS\(\)|MMView\.S\b|V\(\)\.S\b|(?<![.\w])v\.S\b|\.(?:LIB|ENG|H)\b|(?<![.\w"])(?:AP|drawAudio|openAudio|audioLevel)\b(?!")', adapter):
    problems.append('mmAdapter.js touches the view\'s state (S(), MMView.S, LIB, ENG, H or the panel\'s globals)')
# ... and never its markup: what it shows goes through MMView's setters
code = re.sub(r'/\*.*?\*/|//[^\n]*', '', adapter, flags=re.S)
for pat, what in [(r'(?<![\w.])\$\(', '$('), (r'(?<![\w.])\$\$\(', '$$('), (r'\bdocument\.', 'document.')]:
    if re.search(pat, code):
        problems.append('mmAdapter.js uses the markup (%s): show it through an MMView setter' % what)
# the view exports no state and no test: those are a diagnostics build's (window.MMDiagnostics)
problems += ['MMView exports %s: only window.MMDiagnostics may carry it' % x for x in sorted(exported & {'S', 'audioSelfTest'})]
# the pages against the contract: ops, arguments, capabilities
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import page_contract_check as pc
schema = pc.load(R + 'doc/modern-ux/mm-data-contract.schema.json')
table = pc.command_table(schema)
problems += pc.check_sends(list(pc.literals_with_op(adapter)), table, 'mmAdapter.js')
problems += pc.check_audio(js, table, 'mmMockup.js')
na_sel = re.search(r'const NA_SEL=\{(.*?)\};', js, re.S)
na_info = re.search(r'const NA_INFO=\[(.*?)\];', js, re.S)
if not na_sel or not na_info:
    problems.append('the mockup has no NA_SEL / NA_INFO')
else:
    problems += pc.check_caps(re.findall(r'(?:^|[,{\n])\s*(\w+):', na_sel.group(1)), re.findall(r'"(\w+)"', na_info.group(1)), schema, 'the mockup')
problems += pc.check_mapping_gate(js, ['setMapping(!window.MMHost)', 'if(ws==="control"&&!S.mapping)return', 'S.mapping&&(e.key==="l"'], 'the mockup')
problems += pc.check_mapping_gate(adapter, ['V().setMapping(!!doc.enabled)'], 'mmAdapter.js')
# both ways: every host call the mockup makes is one the adapter has, and every one it has is made
host_calls = set(re.findall(r'HOST\.(\w+)', js))
host_block = adapter[adapter.index('window.MMHost = {'):]
host_block = host_block[:host_block.index('\n\t};\n')]
host_methods = set(re.findall(r'^\t\t(\w+)(?:\(|:)', host_block, re.M))
problems += ['the mockup calls HOST.%s, which mmAdapter.js does not have' % x for x in sorted(host_calls - host_methods)]
problems += ['mmAdapter.js has host call %s, which the mockup never makes' % x for x in sorted(host_methods - host_calls)]
# LIFE (machine.lifecycle -> the mockup's engine states) and the message types onMessage handles,
# both against the contract, both ways.
life = pc.find_object(adapter, 'LIFE')
if life is None:
    problems.append('mmAdapter.js: no LIFE')
else:
    problems += pc.check_lifecycle(pc.object_keys(life) or set(), schema, 'mmAdapter.js')
problems += pc.check_message_types(pc.message_types_handled(adapter), schema, 'mmAdapter.js')
if problems:
    print('contract check: ' + '; '.join(problems))
    sys.exit(1)

outs = [('mmStudio.html', page), ('mmStudio.css', out_css), ('mmMockup.js', out_js)]
if check_only:
    drift = [n for n, text in outs if not os.path.exists(SK + n) or open(SK + n).read() != text]
    print('drift: ' + ', '.join(drift) if drift else 'in step with the mockup')
    sys.exit(1 if drift else 0)
for n, text in outs:
    open(SK + n, 'w').write(text)
print('synced: %d bytes markup, %d bytes stylesheet, %d bytes script; %d view members, %d host calls and %d ids checked (self-tests: %d members, %d ids)'
      % (len(page), len(out_css), len(out_js), len(used), len(host_methods), len(wanted), len(test_used), len(test_wanted)))
