#!/usr/bin/env node
"use strict";
/* Both editors' key maps as data (K0, doc/modern-ux/DESIGN-keymap.md): every Keys.bind entry of the Machinedrum
   Editor's page (its scripts, as mdStudio.html loads them) and of the Monomachine Editor's (the generated
   mmMockup.js), made as the pages make them, on a stand-in DOM that answers everything and does nothing (as the
   keys tests run them). Written to doc/modern-ux/keymap.json, and the guide's key tables
   (site/public/guide/index.html, between the keymap markers) are generated from the same data, so neither can
   drift from the editors.
     node scripts/keymap-export.js           write both
     node scripts/keymap-export.js --check   exit 1 when either differs from what is committed
   Required by the tests (skins/shared/deskKeymapTest.js) for load(), entries() and guide(). */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const SKINS = path.join(ROOT, "source/elektron/md/mdJucePlugin/skins");
const JSON_OUT = path.join(ROOT, "doc/modern-ux/keymap.json");
const GUIDE = path.join(ROOT, "site/public/guide/index.html");
const BEGIN = "<!-- keymap:begin: generated by scripts/keymap-export.js from both editors' key maps; do not edit by hand -->";
const END = "<!-- keymap:end -->";

/* the page's scripts in load order: the MD page's from its markup (less the self-tests), the MM page's UI script */
function files(which) {
	if (which === "mm") return [path.join(SKINS, "mmStudio/mmMockup.js")];
	const html = fs.readFileSync(path.join(SKINS, "mdStudio/mdStudio.html"), "utf8");
	return [...html.matchAll(/<script src="([\w.]+)"><\/script>/g)].map(m => m[1]).filter(f => !/SelfTest\.js$/.test(f))
		.map(f => path.join(SKINS, f.startsWith("desk") ? "shared" : "mdStudio", f));
}
/* the scripts on a stand-in: every unknown name is "any" (callable, constructible, every property any); returns
   the page's Keys (and the scope, for a test that wants a page name); navigator says the platform asked for */
function load(which, opts = {}) {
	const any = new Proxy(function () { }, {
		get: (t, k) => k === Symbol.toPrimitive ? () => 0 : k === Symbol.iterator ? function* () { } : k === "length" ? 0 : any,
		apply: () => any, construct: () => any, has: () => false, set: () => true });
	const real = { Math, JSON, Object, Array, String, Number, Boolean, Set, Map, WeakMap, WeakSet, Symbol, Promise, Date, RegExp, Error, TypeError, parseInt, parseFloat, isNaN, isFinite,
		Uint8Array, Int8Array, Uint16Array, Int16Array, Uint32Array, Int32Array, Float32Array, Float64Array, DataView, ArrayBuffer, encodeURIComponent, decodeURIComponent,
		console: { log() { }, info() { }, warn() { }, error() { }, debug() { } },	/* the pages' start-up lines are not the map */
		Infinity, NaN, undefined, URLSearchParams, location: { hash: "", search: "" },
		navigator: { platform: opts.platform || "MacIntel", userAgent: "" } };
	const scope = new Proxy({}, {
		has: () => true,
		get: (t, k) => k === Symbol.unscopables ? undefined : k in t ? t[k] : k in real ? real[k] : any,
		set: (t, k, v) => { t[k] = v; return true; } });
	const src = files(which).map(f => fs.readFileSync(f, "utf8").replace(/^"use strict";/, "")).join("\n;\n")
		.replace(/^render\(\);\s*$/m, "").replace(/^Bridge\.ready\(\);\s*$/m, "");
	return new Function("scope", "with (scope) {\n" + src + "\n;return Keys; }")(scope);
}
const textOf = b => { let t; try { t = typeof b.does === "function" ? String(b.does()) : String(b.does || ""); } catch (_) { t = ""; } return t.replace(/\s*\(now [^)]*\)\s*$/, ""); };
/* an entry as plain data (what a rebinding, the guide and the keyboard view read) */
function entries(Keys) {
	return Keys.list().map(b => {
		const o = { id: b.id, scope: b.scope, keys: b.keys.slice(), mod: b.mod || "", group: b.group, does: textOf(b) };
		for (const k of ["area", "code", "short", "modal"]) if (b[k] != null) o[k] = b[k];
		for (const k of ["hidden", "mapping", "field", "tip"]) if (b[k]) o[k] = true;
		if (b.run) o.dispatched = true;
		return o;
	});
}

/* ---- the guide's tables ---- */
const GROUPS = ["Playing", "Selected track", "All", "Transport", "Workspaces", "Sequence", "Song", "Values", "Anywhere", "Kit library, pattern chooser", "Help"];
const AREAS = ["Steps", "Roll", "Lock lane", "GEN bar", "Tracks", "Values", "Top bar", "LCD", "Song", "Sampler", "Library"];
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const SYM = { cmd: "⌘", alt: "⌥", shift: "⇧" };
const NAMES = { Space: "Space", ArrowLeft: "←", ArrowRight: "→", ArrowUp: "↑", ArrowDown: "↓", Escape: "Esc", Delete: "Delete", Backspace: "Backspace", Enter: "Enter" };
const kbd = k => `<kbd>${esc(NAMES[k] || k)}</kbd>`;
function keyCell(e) {
	const mods = e.mod ? e.mod.split("+").map(m => kbd(SYM[m])).join(" ") + " " : "";
	if (e.area) return mods + esc(e.keys.join(" / "));
	const keys = e.keys.map(k => /^[A-Z0-9](?: [A-Z0-9])+$/.test(k) ? k.split(" ").map(kbd).join(" ") : kbd(k)).join(" / ");
	return mods + keys;
}
const shown = e => !e.hidden && !e.mapping && !e.tip;
/* one row per id: the MD entry's words, the MM entry's where they differ, a machine's own entry marked so */
function rows(md, mm, pick) {
	const out = [], mmById = new Map(mm.filter(pick).map(e => [e.id, e])), done = new Set();
	for (const a of md.filter(pick)) {
		const b = mmById.get(a.id); done.add(a.id);
		if (!b) { out.push({ key: keyCell(a), text: "MD: " + esc(a.does) }); continue; }
		const ka = keyCell(a), kb = keyCell(b);
		const key = ka === kb ? ka : `${ka} <small>(MM: ${kb})</small>`;
		out.push({ key, text: a.does === b.does ? esc(a.does) : `MD: ${esc(a.does)}<br>MM: ${esc(b.does)}` });
	}
	for (const b of mm.filter(pick)) if (!done.has(b.id)) out.push({ key: keyCell(b), text: "MM: " + esc(b.does) });
	return out;
}
const table = rs => `    <div class="tablewrap"><table><tbody>\n${rs.map(r => `      <tr><th scope="row">${r.key}</th><td>${r.text}</td></tr>`).join("\n")}\n    </tbody></table></div>`;
function guide(md, mm) {
	const parts = [];
	const groups = [...GROUPS, ...new Set([...md, ...mm].filter(e => shown(e) && !e.area && !GROUPS.includes(e.group)).map(e => e.group))];
	for (const g of groups) {
		const rs = rows(md, mm, e => shown(e) && !e.area && e.group === g);
		if (rs.length) parts.push(`    <h3>${esc(g)}</h3>\n` + table(rs));
	}
	const areas = [...AREAS, ...new Set([...md, ...mm].filter(e => shown(e) && e.area && !AREAS.includes(e.area)).map(e => e.area))];
	for (const a of areas) {
		const rs = rows(md, mm, e => shown(e) && e.area === a);
		if (rs.length) parts.push(`    <h3>Mouse: ${esc(a)}</h3>\n` + table(rs));
	}
	return BEGIN + "\n" + parts.join("\n\n") + "\n    " + END;
}
function guideWith(html, md, mm) {
	const a = html.indexOf(BEGIN), b = html.indexOf(END);
	if (a < 0 || b < a) throw new Error("the guide has no keymap markers: " + GUIDE);
	return html.slice(0, a) + guide(md, mm) + html.slice(b + END.length);
}
function build() {
	const md = entries(load("md")), mm = entries(load("mm"));
	const json = JSON.stringify({ about: "Both editors' key maps (scripts/keymap-export.js; doc/modern-ux/DESIGN-keymap.md). Generated: do not edit.", md, mm }, null, "\t") + "\n";
	return { md, mm, json, html: guideWith(fs.readFileSync(GUIDE, "utf8"), md, mm) };
}
module.exports = { load, entries, guide, build, JSON_OUT, GUIDE };

if (require.main === module) {
	const out = build(), check = process.argv.includes("--check");
	const now = [[JSON_OUT, out.json], [GUIDE, out.html]];
	if (check) {
		const drift = now.filter(([f, t]) => !fs.existsSync(f) || fs.readFileSync(f, "utf8") !== t).map(([f]) => path.relative(ROOT, f));
		console.log(drift.length ? "keymap drift: " + drift.join(", ") + " (run node scripts/keymap-export.js)" : "keymap: in step");
		process.exit(drift.length ? 1 : 0);
	}
	for (const [f, t] of now) fs.writeFileSync(f, t);
	console.log(`keymap: ${out.md.length} MD and ${out.mm.length} MM entries written`);
}
