name: MD/MM cross-platform prerelease

on:
  push:
    tags:
      - "mdmm-v*"

permissions:
  contents: read

jobs:
  build-windows:
    uses: ./.github/workflows/elektron-windows.yml

  build-macos:
    uses: ./.github/workflows/elektron-macos.yml
